config/routes.rb
Rails.application.routes.draw do
  #get 'inappropiate_comments/new'
  #get 'inappropiate_comments/create'
  #get 'inappropiate_comments/destroy'
  #get 'inappropiate_comments/update'
  resources :probandos
  root to: 'home#index'
  resources :flags, only: [:create]
  get 'flags/create'
  get 'policy/index'
  get 'users/index', as: "profile"
  get 'users/show'
  get 'users/edit_user', as: "edit_user"
  resources :users, only: [:update]
  get 'posts/index', as: 'posts_index'
  get 'posts/edit_post', as: 'edit_post'
  
  resources :posts
  post 'users/update'
  get 'users/enable_admin', to: 'users#enable_admin', as: 'enable_admin'
  get 'users/unable_admin', to: 'users#unable_admin', as: 'unable_admin'
  get 'users/enable_superadmin', to: 'users#enable_superadmin', as: 'enable_superadmin'
  get 'users/unable_superadmin', to: 'users#unable_superadmin', as: 'unable_superadmin'
  resources :users, only: [:enable_admin, :unable_admin, :enable_superadmin, :unable_superadmin]
  resources :comments
  resources :likes, only: [:create, :destroy]
  resources :inappropiate_comments, only: [:create, :destroy]
  resources :inappropiate_posts, only: [:create, :destroy]
  resources :flags, only: [:create, :destroy]
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'callbacks' }
  # si falla omniauth añadir passthru a callbacks controller
  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blacklist.rb
class Blacklist < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	has_many :inappropiate_comments, dependent: :delete_all
	validates :description, presence: true
	validates :description, length: { in: 1..1000, too_long: "1000 characters is the maximum allowed" }

end

app/models/dumpster.rb
class Dumpster < ApplicationRecord
	belongs_to :post
end

app/models/flag.rb
class Flag < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/inappropiate_comment.rb
class InappropiateComment < ApplicationRecord
	belongs_to :comment
	belongs_to :user
	validates :justification, length: { maximum: 60 , too_long: "60 characters is the maximum allowed" }
	validates :user_id, uniqueness: { scope: :comment_id }
end

app/models/inappropiate_post.rb
class InappropiatePost < ApplicationRecord
	belongs_to :post
	belongs_to :user
	validates :justification, length: { maximum: 60 , too_long: "60 characters is the maximum allowed" }
	validates :user_id, uniqueness: { scope: :post_id }

end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :user_id, uniqueness: { scope: :post_id }

end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :inappropiate_posts, dependent: :delete_all
	has_one :blacklist
	has_one :dumpster
	has_many :comments, dependent: :delete_all
	has_many :flags, dependent: :delete_all
	has_many_attached :files
	has_many :likes, dependent: :delete_all
	validates :title, :description, :user_id, presence: true	
	validates :title, length: { in: 1..100, too_long: "100 characters is the maximum allowed" }
	validates :description, length: { in: 1..1250, too_long: "1250 characters is the maximum allowed" } 
end

app/models/probando.rb
class Probando < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]
	has_many :posts, dependent: :delete_all
	has_many :comments, through: :posts, dependent: :delete_all
	has_many :inappropiate_posts, dependent: :delete_all
	has_many :inappropiate_comments, dependent: :delete_all
	has_one :blacklist
	has_many :likes, dependent: :delete_all
	has_many :flags, dependent: :delete_all
	validates :name, presence: true
	validates :city, presence: true
	validates :country, presence: true
	has_one_attached :image
	after_create :image_is_attached
	def image_is_attached
		if !self.image.attached?
			self.image.attach(io: File.open(Rails.root.join("app","assets","images","nophoto.png")), filename: 'nophoto.png', content_type: "image/png")
		end
	end

	
	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.email = auth.info.email
			user.name = auth.info.email
			user.password = Devise.friendly_token[0,20]
		end
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment_new = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_back(fallback_location: root_path) 
    else
    	flash[:danger] = "Error. Try it later"
	redirect_back(fallback_location: root_path)    
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :description)
    end
end

app/controllers/flags_controller.rb
class FlagsController < ApplicationController
  def create
		@flag = current_user.flags.build(flag_params)
		if @flag.save
			flash[:success] = 'Post flagged' 
			@post = @flag.post.id		
			redirect_back(fallback_location: root_path) 
		else
			flash[:errors] = "Error: Something happen. Try it later"
			redirect_to "/"
		end
  end

  def destroy
	@flag = Flag.find(params[:id])
    	@flag.destroy
    	flash[:danger] = "Unflag the post"
    	redirect_back(fallback_location: root_path)
  end
  def flag_params
		params.require(:flag).permit(:post_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	@comment_new = Comment.new
	@comments = Comment.all.order("created at DESC")
	@post_new = Post.new
	@posts = Post.all.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/policy_helper.rb
module PolicyHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	
end

app/helpers/probandos_helper.rb
module ProbandosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<center>
  <%= form_with(model: comment, local: true) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <center>
      <div class="panel panel-success" style="width: 600px; height: auto;">
        <div class="panel-heading">
          <div class="float-left">
            <%= image_tag(current_user.image, size:'25x35') %>
          </div>
          <center> <h4> What do you think about that? </h4></center>
        </div>
        <div class="panel-body">
          <div class="field">
            <%= form.label :description %>
            <%= form.text_area :description, cols: 55, rows: 1 %>
          </div>
        </div>
        <div class="panel-footer" style="height: 55px;">
          <div class="float-right">
            <div class="actions">
              <%= form.submit %>
              <%= form.hidden_field :post_id, value: @post.id %>
            </div>
          </div>
        </div>
      </div>
    </center>
  <% end %>
</center>

app/views/comments/_show.html.erb
<center>
	<% @comments.each do |comment| %>
		<div class="panel panel-default" style="width: 550px; height: auto;">
			<% if comment.post_id == @post.id %>
				<div class="panel-heading">
					<% if comment.user_id == current_user.id %>
	            		<a href="/users/index"> <%= image_tag(current_user.image, size:'25x45') %> </a>
	            		<a style="font-size: 25px;"> <%= link_to current_user.name, profile_path %> </a>
	        		<% else %>
			            <a href="/users/show"> <%= image_tag(comment.user.image, size:'20x30') %> </a>
			            <a style = "font-size: 15px;"> <%= link_to comment.user.name, users_show_path(user_id: comment.user.id) %> </a>  
	        		<% end %>
				</div>
				<div class="panel-body">
					<a> <%= comment.description %> </a>
				</div>
				<div class="panel-footer">
					<div class="row">
						<% inappropiate_comment = comment.inappropiate_comments.where("user_id = ?", current_user.id) %>
                  		<center> <a>
                  		<% if inappropiate_comment.empty? %>
                    		<%= button_to inappropiate_comments_path(inappropiate_comment: {comment_id: comment.id}), method: :post, class:"btn btn-light btn-sm" do %>
                      			<span class="glyphicon glyphicon-fire"> <%= comment.inappropiate_comments.count %> </span> 
                    		<% end %>
                  		<% else %>
                    		<%= button_to inappropiate_comment.first, method: :delete, class:"btn btn-light btn-sm" do %>
                      			<span class="glyphicon glyphicon-erase"> <%= comment.inappropiate_comments.count %> </span>
                    		<% end %>
                  		<% end %>
                  		</a> </center>
					</div>
				</div>
			<% end %>
		</div>
	<% end %>
</center>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Index</th>
      <th>Show</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.index %></td>
        <td><%= comment.show %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Index:</strong>
  <%= @comment.index %>
</p>

<p>
  <strong>Show:</strong>
  <%= @comment.show %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>