config/routes.rb
Rails.application.routes.draw do
  #get 'inappropiate_comments/new'
  #get 'inappropiate_comments/create'
  #get 'inappropiate_comments/destroy'
  #get 'inappropiate_comments/update'
  resources :probandos
  root to: 'home#index'
  resources :flags, only: [:create]
  get 'flags/create'
  get 'policy/index'
  get 'users/index', as: "profile"
  get 'users/show'
  get 'users/edit_user', as: "edit_user"
  resources :users, only: [:update]
  get 'posts/index', as: 'posts_index'
  get 'posts/edit_post', as: 'edit_post'
  
  resources :posts
  post 'users/update'
  get 'users/enable_admin', to: 'users#enable_admin', as: 'enable_admin'
  get 'users/unable_admin', to: 'users#unable_admin', as: 'unable_admin'
  get 'users/enable_superadmin', to: 'users#enable_superadmin', as: 'enable_superadmin'
  get 'users/unable_superadmin', to: 'users#unable_superadmin', as: 'unable_superadmin'
  resources :users, only: [:enable_admin, :unable_admin, :enable_superadmin, :unable_superadmin]
  resources :comments
  resources :likes, only: [:create, :destroy]
  resources :inappropiate_comments, only: [:create, :destroy]
  resources :inappropiate_posts, only: [:create, :destroy]
  resources :flags, only: [:create, :destroy]
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'callbacks' }
  # si falla omniauth añadir passthru a callbacks controller
  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blacklist.rb
class Blacklist < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	has_many :inappropiate_comments, dependent: :delete_all
	validates :description, presence: true
	validates :description, length: { in: 1..1000, too_long: "1000 characters is the maximum allowed" }

end

app/models/dumpster.rb
class Dumpster < ApplicationRecord
	belongs_to :post
end

app/models/flag.rb
class Flag < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/inappropiate_comment.rb
class InappropiateComment < ApplicationRecord
	belongs_to :comment
	belongs_to :user
	validates :justification, length: { maximum: 60 , too_long: "60 characters is the maximum allowed" }
	validates :user_id, uniqueness: { scope: :comment_id }
end

app/models/inappropiate_post.rb
class InappropiatePost < ApplicationRecord
	belongs_to :post
	belongs_to :user
	validates :justification, length: { maximum: 60 , too_long: "60 characters is the maximum allowed" }
	validates :user_id, uniqueness: { scope: :post_id }

end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :user_id, uniqueness: { scope: :post_id }

end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :inappropiate_posts, dependent: :delete_all
	has_one :blacklist
	has_one :dumpster
	has_many :comments, dependent: :delete_all
	has_many :flags, dependent: :delete_all
	has_many_attached :files
	has_many :likes, dependent: :delete_all
	validates :title, :description, :user_id, presence: true	
	validates :title, length: { in: 1..100, too_long: "100 characters is the maximum allowed" }
	validates :description, length: { in: 1..1250, too_long: "1250 characters is the maximum allowed" } 
end

app/models/probando.rb
class Probando < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]
	has_many :posts, dependent: :delete_all
	has_many :comments, through: :posts, dependent: :delete_all
	has_many :inappropiate_posts, dependent: :delete_all
	has_many :inappropiate_comments, dependent: :delete_all
	has_one :blacklist
	has_many :likes, dependent: :delete_all
	has_many :flags, dependent: :delete_all
	validates :name, presence: true
	validates :city, presence: true
	validates :country, presence: true
	has_one_attached :image
	after_create :image_is_attached
	def image_is_attached
		if !self.image.attached?
			self.image.attach(io: File.open(Rails.root.join("app","assets","images","nophoto.png")), filename: 'nophoto.png', content_type: "image/png")
		end
	end

	
	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.email = auth.info.email
			user.name = auth.info.email
			user.password = Devise.friendly_token[0,20]
		end
	end
end

app/controllers/flags_controller.rb
class FlagsController < ApplicationController
  def create
		@flag = current_user.flags.build(flag_params)
		if @flag.save
			flash[:success] = 'Post flagged' 
			@post = @flag.post.id		
			redirect_back(fallback_location: root_path) 
		else
			flash[:errors] = "Error: Something happen. Try it later"
			redirect_to "/"
		end
  end

  def destroy
	@flag = Flag.find(params[:id])
    	@flag.destroy
    	flash[:danger] = "Unflag the post"
    	redirect_back(fallback_location: root_path)
  end
  def flag_params
		params.require(:flag).permit(:post_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	@comment_new = Comment.new
	@comments = Comment.all.order("created at DESC")
	@post_new = Post.new
	@posts = Post.all.order("created_at DESC")
  end
end

app/controllers/probandos_controller.rb
class ProbandosController < ApplicationController
  before_action :set_probando, only: [:show, :edit, :update, :destroy]

  # GET /probandos
  # GET /probandos.json
  def index
    @probandos = Probando.all
  end

  # GET /probandos/1
  # GET /probandos/1.json
  def show
  end

  # GET /probandos/new
  def new
    @probando = Probando.new
  end

  # GET /probandos/1/edit
  def edit
  end

  # POST /probandos
  # POST /probandos.json
  def create
    @probando = Probando.new(probando_params)

    respond_to do |format|
      if @probando.save
        format.html { redirect_to @probando, notice: 'Probando was successfully created.' }
        format.json { render :show, status: :created, location: @probando }
      else
        format.html { render :new }
        format.json { render json: @probando.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /probandos/1
  # PATCH/PUT /probandos/1.json
  def update
    respond_to do |format|
      if @probando.update(probando_params)
        format.html { redirect_to @probando, notice: 'Probando was successfully updated.' }
        format.json { render :show, status: :ok, location: @probando }
      else
        format.html { render :edit }
        format.json { render json: @probando.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /probandos/1
  # DELETE /probandos/1.json
  def destroy
    @probando.destroy
    respond_to do |format|
      format.html { redirect_to probandos_url, notice: 'Probando was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_probando
      @probando = Probando.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def probando_params
      params.require(:probando).permit(:user_id, :post_id, :parragraph, :number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/policy_helper.rb
module PolicyHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	
end

app/helpers/probandos_helper.rb
module ProbandosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/probandos/_form.html.erb
<%= form_with(model: probando, local: true) do |form| %>
  <% if probando.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(probando.errors.count, "error") %> prohibited this probando from being saved:</h2>

      <ul>
      <% probando.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="field">
    <%= form.label :parragraph %>
    <%= form.text_field :parragraph %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/probandos/edit.html.erb
<h1>Editing Probando</h1>

<%= render 'form', probando: @probando %>

<%= link_to 'Show', @probando %> |
<%= link_to 'Back', probandos_path %>

app/views/probandos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Probandos</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Post</th>
      <th>Parragraph</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @probandos.each do |probando| %>
      <tr>
        <td><%= probando.user %></td>
        <td><%= probando.post %></td>
        <td><%= probando.parragraph %></td>
        <td><%= probando.number %></td>
        <td><%= link_to 'Show', probando %></td>
        <td><%= link_to 'Edit', edit_probando_path(probando) %></td>
        <td><%= link_to 'Destroy', probando, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Probando', new_probando_path %>

app/views/probandos/new.html.erb
<h1>New Probando</h1>

<%= render 'form', probando: @probando %>

<%= link_to 'Back', probandos_path %>

app/views/probandos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @probando.user %>
</p>

<p>
  <strong>Post:</strong>
  <%= @probando.post %>
</p>

<p>
  <strong>Parragraph:</strong>
  <%= @probando.parragraph %>
</p>

<p>
  <strong>Number:</strong>
  <%= @probando.number %>
</p>

<%= link_to 'Edit', edit_probando_path(@probando) %> |
<%= link_to 'Back', probandos_path %>