config/routes.rb
Rails.application.routes.draw do
  #get 'inappropiate_comments/new'
  #get 'inappropiate_comments/create'
  #get 'inappropiate_comments/destroy'
  #get 'inappropiate_comments/update'
  resources :probandos
  root to: 'home#index'
  resources :flags, only: [:create]
  get 'flags/create'
  get 'policy/index'
  get 'users/index', as: "profile"
  get 'users/show'
  get 'users/edit_user', as: "edit_user"
  resources :users, only: [:update]
  get 'posts/index', as: 'posts_index'
  get 'posts/edit_post', as: 'edit_post'
  
  resources :posts
  post 'users/update'
  get 'users/enable_admin', to: 'users#enable_admin', as: 'enable_admin'
  get 'users/unable_admin', to: 'users#unable_admin', as: 'unable_admin'
  get 'users/enable_superadmin', to: 'users#enable_superadmin', as: 'enable_superadmin'
  get 'users/unable_superadmin', to: 'users#unable_superadmin', as: 'unable_superadmin'
  resources :users, only: [:enable_admin, :unable_admin, :enable_superadmin, :unable_superadmin]
  resources :comments
  resources :likes, only: [:create, :destroy]
  resources :inappropiate_comments, only: [:create, :destroy]
  resources :inappropiate_posts, only: [:create, :destroy]
  resources :flags, only: [:create, :destroy]
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'callbacks' }
  # si falla omniauth añadir passthru a callbacks controller
  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]
	has_many :posts, dependent: :delete_all
	has_many :comments, through: :posts, dependent: :delete_all
	has_many :inappropiate_posts, dependent: :delete_all
	has_many :inappropiate_comments, dependent: :delete_all
	has_one :blacklist
	has_many :likes, dependent: :delete_all
	has_many :flags, dependent: :delete_all
	validates :name, presence: true
	validates :city, presence: true
	validates :country, presence: true
	has_one_attached :image
	after_create :image_is_attached
	def image_is_attached
		if !self.image.attached?
			self.image.attach(io: File.open(Rails.root.join("app","assets","images","nophoto.png")), filename: 'nophoto.png', content_type: "image/png")
		end
	end

	
	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.email = auth.info.email
			user.name = auth.info.email
			user.password = Devise.friendly_token[0,20]
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_user, only: [:index, :show, :edit, :update]	
	#before_action :set_user, except: [:create]
	before_action :authenticate_user!, except: [:index, :show]
  	def index
		@post_new = Post.new
		@comment_new = Comment.new
		@posts = current_user.posts.order("created_at DESC")
  	end

	def show
		@user = User.find(params[:user_id])
		@post_new = Post.new
		@comment_new = Comment.new
		@posts = @user.posts.order("created_at DESC")	
  	end
	
	def user_params
		
		params.require(:user).permit(:image, :name, :city, :country, :email, :password, :sex)
	end

	def google_user_params
		params.require(:user).permit(:image, :name, :email, :password, :provider, :uid)
	end
	def new

	end

	def create
		if current_user.uid != nil
			@user = User.new(google_user_params)
			if @user.save
        			format.html { redirect_to root_url, notice: 'User was successfully created.' }
        			#format.json { render :show, status: :created, location: @user }
      			else
        			format.html { render :new }
        			#format.json { render json: @user.errors, status: :unprocessable_entity }
      			end
		else
			@user = User.new(user_params)
			if @user.save
        			format.html { redirect_to root_url, notice: 'User was successfully created.' }
        			#format.json { render :show, status: :created, location: @user }
      			else
        			format.html { render :new }
        			#format.json { render json: @user.errors, status: :unprocessable_entity }
      			end
		end
	end

  	

	def enable_admin
		@user = User.find(params[:user_id])
		@user.role = "Admin"
		@user.save
		redirect_to users_show_url(user_id: @user.id)
	end
	
	def unable_admin
		@user = User.find(params[:user_id])
		@user.role = nil
		@user.save
		redirect_to users_show_url(user_id: @user.id)
	end

	def enable_superadmin
		@user = User.find(params[:user_id])
		@user.role = "SuperAdmin"
		@user.save
		redirect_to users_show_url(user_id: @user.id)
	end
	
	def unable_superadmin
		@user = User.find(params[:user_id])
		@user.role = "Admin"
		@user.save
		redirect_to users_show_url(user_id: @user.id)
	end
	
	def edit_user
		@user = User.find(params[:user_id])
  	end	

	def update
		@user = User.find(params[:user_id])
		respond_to do |format|
	      		if @user.update(update_user_params)
				flash[:success] = "User was successfully edited"
				redirect_to users_show_url(user_id: @user.id)
	      		else
				flash[:danger] = "Error. Try it later"
				redirect_to users_show_url(user_id: @user.id)
	      		end
    		end
	end
	
	def update_user_params
		params.require(:user).permit(:name, :biography)
	end
	#private	
	
	#def set_user
	#	@user = User.find(params[:id])	
	#end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/edit_user.html.erb
<div class="container">
	<div class="jumbotron">
		<center>
			<h2> Edit User </h2>
			<%= form_for(@user) do |form| %>
				<% if @user.errors.any? %>
    				<div id="error_explanation">
	      				<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

	      				<ul>
	      				<% @user.errors.full_messages.each do |message| %>
	        				<li><%= message %></li>
	      				<% end %>
	      				</ul>
    				</div>
  				<% end %>
				<div class="field">
					<%= form.label :name %><br />
					<%= form.text_field :name, autofocus: true, autocomplete: 'name' %>
				</div>

				<div class="field">
					<%= form.label :biography %><br />
					<%= form.text_area :biography, rows: 6, cols: 60 %>
				</div>

				<div class="actions">
					<%= form.submit "Update User" %>
				</div>
			<% end %>
		</center>
	</div>
</div>

app/views/users/index.html.erb
<style>
	.form{
		width: 500px;
	}

</style>
<div class="container website" style="padding-bottom: 30px;" >
	</br>
	<div class="row">
		<div class="col-sm-4">
			<%= image_tag(current_user.image, style:"width: 250px; height: auto;" )%>
		</div>

		<div class="col-sm-4">
			<table class="table table-bordered">
				<thead class="thead-dark">
					<tr>
						<th scope="col">
							<center> <h1 style="color: white;"> <%= current_user.name %> </h1> </center> 		
						</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th scope="row">
							<center> <p style="font-size: 20px;"> <%= current_user.sex %> </p> </center>
						</th>
					</tr>
					<tr>
						<th scope="row">
							<center> <p style="font-size: 15px;"> <%= current_user.city %>, <%= current_user.country %> </p> </center>
						</th>
					</tr>
					<tr>
						<th scope="row">
							<center> <p style="font-size: 15px;"> <%= current_user.biography %> </p> </center>
						</th>
					</tr>
				</tbody>
			</table>
		</div>

		<div class="col-sm-4">
			<div class="float-right">
				<button type="button" class="btn btn- btn-sm" style="background-color: black ; border: white; font-weight: bold ">
					<%= link_to 'Edit your profile', edit_user_registration_path %>
				</button>
			</div>
		</div>
	</div>
	<center> <h1> Post something ... </h1> </br> </center>
	<div class="row justify-content-md-center" style="margin-top: 5px;">
		<%= render :partial => 'posts/form', :locals => { :post => @post_new } %>
		<%= render :partial => "posts/show" %>
	</div>
</div>
	

app/views/users/show.html.erb
<style>
	.form{
		width: 500px;
	}

</style>
<div class="container website" style="padding-bottom: 30px;" >
	</br>
	<div class="row">
		<div class="col-sm-4">
			<%= image_tag(@user.image, style:"width: 250px; height: auto;" )%>
		</div>

		<div class="col-sm-4">
			<table class="table table-bordered">
				<thead class="thead-dark">
					<tr>
						<th scope="col"> 
							<center> <h1 style="color: white;"> <%= @user.name %> </h1> </center> 		
						</th>
					</tr>
				</thead>
				<tbody>
						<tr>
							<th scope="row">
								<center> <p style="font-size: 20px;"> <%= @user.sex %> </p> </center>
							</th>
						</tr>
						<tr>
							<th scope="row">
								<center> <p style="font-size: 15px;"> <%= @user.city %>, <%= @user.country %> </p> </center>
							</th>
						</tr>
						<tr>
							<th scope="row">
								<center> <p style="font-size: 15px;"> <%= @user.biography %> </p></center>
							</th>
						</tr>
				</tbody>
			</table>
		</div>

		<div class="col-sm-4">
			<div class="float-right">
				<% if current_user.role == "SuperAdmin" && current_user.email == "super@admin.cl" %>
					<% if @user.role != "SuperAdmin" %>
						<button type="button" class="btn btn-success btn-md" style="font-weight: bold; margin-right: 5px; color: white;" >
						<%= link_to 'Enable SuperAdmin', enable_superadmin_path(user_id: @user.id) %>   
						</button>
					<% else %>
						<button type="button" class="btn btn-md" style="font-weight: bold; margin-right: 5px; color: white; background-color: red;" >
						<%= link_to 'Unable SuperAdmin', unable_superadmin_path(user_id: @user.id) %>
						</button>
					<% end %>
				<% end %>
				<% if current_user.role == "SuperAdmin" %>
					<% if @user.role != "Admin" %>
						<button type="button" class="btn btn-success btn-md" style="font-weight: bold; margin-right: 5px; color: white;">
						<%= link_to 'Enable Admin', enable_admin_path(user_id: @user.id) %>  
						</button>
					<% else %>
						<button type="button" class="btn btn-md" style="font-weight: bold; margin-right: 5px; color: white; background-color: red;">
						<%= link_to 'Unable Admin', unable_admin_path(user_id: @user.id) %> 
						</button>
					<% end %>
				<% end %>
				<% if current_user.role == "SuperAdmin" || current_user.role == "Admin"%>
					<button type="button" class="btn btn-warning btn-md" style="font-weight: bold; color: white;">
						<%= link_to "Edit User", edit_user_path(user_id: @user.id) %>
					</button>
				<% end %>
			</div>
		</div>
	</div>
	<center> <h1> Post something ... </h1> </br> </center>
	<div class="row justify-content-md-center" style="margin-top: 5px;">
		<%= render 'posts/form', post: @post_new  %>
		<%= render :partial => "posts/show" %>
	</div>
</div>