config/routes.rb
Rails.application.routes.draw do
  #get 'inappropiate_comments/new'
  #get 'inappropiate_comments/create'
  #get 'inappropiate_comments/destroy'
  #get 'inappropiate_comments/update'
  resources :probandos
  root to: 'home#index'
  resources :flags, only: [:create]
  get 'flags/create'
  get 'policy/index'
  get 'users/index', as: "profile"
  get 'users/show'
  get 'users/edit_user', as: "edit_user"
  resources :users, only: [:update]
  get 'posts/index', as: 'posts_index'
  get 'posts/edit_post', as: 'edit_post'
  
  resources :posts
  post 'users/update'
  get 'users/enable_admin', to: 'users#enable_admin', as: 'enable_admin'
  get 'users/unable_admin', to: 'users#unable_admin', as: 'unable_admin'
  get 'users/enable_superadmin', to: 'users#enable_superadmin', as: 'enable_superadmin'
  get 'users/unable_superadmin', to: 'users#unable_superadmin', as: 'unable_superadmin'
  resources :users, only: [:enable_admin, :unable_admin, :enable_superadmin, :unable_superadmin]
  resources :comments
  resources :likes, only: [:create, :destroy]
  resources :inappropiate_comments, only: [:create, :destroy]
  resources :inappropiate_posts, only: [:create, :destroy]
  resources :flags, only: [:create, :destroy]
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'callbacks' }
  # si falla omniauth añadir passthru a callbacks controller
  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blacklist.rb
class Blacklist < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	has_many :inappropiate_comments, dependent: :delete_all
	validates :description, presence: true
	validates :description, length: { in: 1..1000, too_long: "1000 characters is the maximum allowed" }

end

app/models/dumpster.rb
class Dumpster < ApplicationRecord
	belongs_to :post
end

app/models/flag.rb
class Flag < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/inappropiate_post.rb
class InappropiatePost < ApplicationRecord
	belongs_to :post
	belongs_to :user
	validates :justification, length: { maximum: 60 , too_long: "60 characters is the maximum allowed" }
	validates :user_id, uniqueness: { scope: :post_id }

end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :user_id, uniqueness: { scope: :post_id }

end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :inappropiate_posts, dependent: :delete_all
	has_one :blacklist
	has_one :dumpster
	has_many :comments, dependent: :delete_all
	has_many :flags, dependent: :delete_all
	has_many_attached :files
	has_many :likes, dependent: :delete_all
	validates :title, :description, :user_id, presence: true	
	validates :title, length: { in: 1..100, too_long: "100 characters is the maximum allowed" }
	validates :description, length: { in: 1..1250, too_long: "1250 characters is the maximum allowed" } 
end

app/models/probando.rb
class Probando < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]
	has_many :posts, dependent: :delete_all
	has_many :comments, through: :posts, dependent: :delete_all
	has_many :inappropiate_posts, dependent: :delete_all
	has_many :inappropiate_comments, dependent: :delete_all
	has_one :blacklist
	has_many :likes, dependent: :delete_all
	has_many :flags, dependent: :delete_all
	validates :name, presence: true
	validates :city, presence: true
	validates :country, presence: true
	has_one_attached :image
	after_create :image_is_attached
	def image_is_attached
		if !self.image.attached?
			self.image.attach(io: File.open(Rails.root.join("app","assets","images","nophoto.png")), filename: 'nophoto.png', content_type: "image/png")
		end
	end

	
	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.email = auth.info.email
			user.name = auth.info.email
			user.password = Devise.friendly_token[0,20]
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	@comment_new = Comment.new
	@comments = Comment.all.order("created at DESC")
	@post_new = Post.new
	@posts = Post.all.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/policy_helper.rb
module PolicyHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	
end

app/helpers/probandos_helper.rb
module ProbandosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/intento de editar post y comments/_show.html.erb
<% @posts.each do |post| %>
	<center>
		<div class="panel panel-info" style = "width: 700px; height: auto;">
			<div class="panel-heading">
			  <% if post.user_id == current_user.id %>
			      <a href="/users/index"> <%= image_tag(current_user.image, size:'35x50') %> </a>
			      <a style="font-size: 30px;"> <%= link_to current_user.name, profile_path %> </a>
			  <% else %>
			      <a href="/users/show"> <%= image_tag(post.user.image, size:'45x55') %> </a>
			      <a style = "font-size: 30px;"> <%= link_to post.user.name, users_show_path(user_id: post.user.id) %> </a>  
			  <% end %>
			</div>
			<div class="panel-body">
				<h2> <%= link_to post.title, posts_index_path(post_id: post.id) %> </h2></br>
				<a> <%= post.description %> </a> </div> </br>
				<% if post.files.attached? %>
					<div class="row" style="margin: 40px;">
						<%= (0...post.files.count).each do |file| %>
						<a> 
							<%= image_tag(post.files[file], style:'width: 150px; height: 100px; margin-right: 10px;') %>	
						</a>
						<% end %>
					</div>
				<% end %>
			</div>
			<div class="panel-footer">
                <div class="row" style="margin-left: 30px;">
                  <a> <span class="glyphicon glyphicon-comment"></span> <%= post.comments.count %> <%= link_to 'Comments', posts_index_path(post_id: post.id) %> </a>
                  <% like = post.likes.where("user_id = ?", current_user.id) %>
                  <a>
                  <% if like.empty? %>
                    <%= button_to likes_path(like: {post_id: post.id}), method: :post, class: "btn btn-light btn-sm" do %>
                        <span class="glyphicon glyphicon-thumbs-up"></span> <%= post.likes.count %>
                    <% end %>
                  <% else %>
                    <%= button_to like.first, method: :delete, class: "btn btn-light btn-sm" do %>
                      <span class="glyphicon glyphicon-thumbs-down"></span> <%= post.likes.count %>
                    <% end %>
                  <% end %>
                  
                  </a>

                  <% inappropiate_post = post.inappropiate_posts.where("user_id = ?", current_user.id) %>
                  <a>
                  <% if inappropiate_post.empty? %>
                    <%= button_to inappropiate_posts_path(inappropiate_post: {post_id: post.id}), method: :post, class:"btn btn-light btn-sm" do %>
                      <span class="glyphicon glyphicon-fire"> <%= post.inappropiate_posts.count %> </span> 
                    <% end %>
                  <% else %>
                    <%= button_to inappropiate_post.first, method: :delete, class:"btn btn-light btn-sm" do %>
                      <span class="glyphicon glyphicon-erase"> <%= post.inappropiate_posts.count %> </span>
                    <% end %>
                  <% end %>
                  </a>
                  <% if current_user.role == "SuperAdmin" or current_user.role == "Admin" %>
                    <% flag = post.flags.where("user_id = ?", current_user.id) %>
                    <a>
                    <% if flag.empty? %>
                      <%= button_to flags_path(flag: {post_id: post.id}), method: :post, class:"btn btn-light btn-sm" do %>
                        <span class="glyphicon glyphicon-flag"> <%= post.flags.count %> </span> 
                      <% end %>
                    <% else %>
                      <%= button_to flag.first, method: :delete, class:"btn btn-light btn-sm" do %>
                        <span class="glyphicon glyphicon-scissors"> <%= post.flags.count %> </span>
                      <% end %> 

                    <% end %>
                    </a>
                  <% end %>
                  <!--
                  <% if current_user.id == post.user_id or current_user.role == "SuperAdmin" or current_user.role == "Admin" %>
                    <a>
                      <button type="button" class="btn btn-light btn-sm">
                        <span class="glyphicon glyphicon-pencil"></span>
                        <%= link_to "Edit Post",  edit_post_path(post_id: post.id) %>
                      </button>  
                    </a>
                  <% end %>
                -->
                </div>
            </div>
		</div>
	<% @post = post %>
	<%= render 'comments/form', comment: @comment_new %>
	</center>
<% end %>

app/views/intento de editar post y comments/edit_post.html.erb
<div class="container">
	<div class="jumbotron">
		<center>
			<h2> Edit Post </h2>
			<%= form_for(@post) do |form| %>
				<% if @post.errors.any? %>
    				<div id="error_explanation">
	      				<h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

	      				<ul>
	      				<% @post.errors.full_messages.each do |message| %>
	        				<li><%= message %></li>
	      				<% end %>
	      				</ul>
    				</div>
  				<% end %>
				<div class="field">
					<%= form.label :title %><br />
					<%= form.text_field :title, autofocus: true, autocomplete: 'title' %>
				</div>

				<div class="field">
					<%= form.label :description %><br />
					<%= form.text_area :description, rows: 6, cols: 60 %>
				</div>

				<div class="actions">
					<%= form.submit "Update Post" %>
				</div>
			<% end %>
		</center>
	</div>
</div>

app/views/intento de editar post y comments/index.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="row">
      <div class="col">
        <center>
          <div class="panel panel-info" style = "width: 700px; height: auto;">
            <div class="panel-heading">
              <% if @post.user_id == current_user.id %>
                  <a href="/users/index"> <%= image_tag(current_user.image, size:'35x50') %> </a>
                  <a style="font-size: 30px;"> <%= link_to current_user.name, profile_path %> </a>
              <% else %>
                  <a > <%= link_to users_show_path(@post.user_id) do %>
                  			<%= image_tag(@post.user.image, size: '55x40') %>  
              	  		<% end %>
              	  </a>  
                  <a style = "font-size: 30px;"> <%= link_to @post.user.name, users_show_path(@post.user_id) %> </a>  
              <% end %>
            </div>
            <div class="panel-body">
              <a style="font-size: 30px; font-weight: bold;" href="/posts/index/"> <%= @post.title %> </a></br>
              <a> <%= @post.description %> </a> </br>
              <% if @post.files.attached? %>
                <div class="row" style="margin: 40px;">
                  <%= (0...@post.files.count).each do |file| %>
                  <a> 
                    <%= image_tag(@post.files[file], style:'width: 150px; height: 100px; margin-right: 10px;') %>  
                  </a>
                  <% end %>
                </div>
              <% end %>
            </div>
            <div class="panel-footer">
                <div class="row" style="margin-left: 30px;">
                  <a> <span class="glyphicon glyphicon-comment"></span> <%= @post.comments.count %> <%= link_to 'Comments', posts_index_path(post_id: @post.id) %> </a>
                  <% like = @post.likes.where("user_id = ?", current_user.id) %>
                  <a>
                  <% if like.empty? %>
                    <%= button_to likes_path(like: {post_id: @post.id}), method: :post, class: "btn btn-light btn-sm" do %>
                        <span class="glyphicon glyphicon-thumbs-up"></span> <%= @post.likes.count %>
                    <% end %>
                  <% else %>
                    <%= button_to like.first, method: :delete, class: "btn btn-light btn-sm" do %>
                      <span class="glyphicon glyphicon-thumbs-down"></span> <%= @post.likes.count %>
                    <% end %>
                  <% end %>
                  
                  </a>
                  <% inappropiate_post = @post.inappropiate_posts.where("user_id = ?", current_user.id) %>
                  <a>
                  <% if inappropiate_post.empty? %>
                    <%= button_to inappropiate_posts_path(inappropiate_post: {post_id: @post.id}), method: :post, class:"btn btn-light btn-sm" do %>
                      <span class="glyphicon glyphicon-fire"> <%= @post.inappropiate_posts.count %> </span> 
                    <% end %>
                  <% else %>
                    <%= button_to inappropiate_post.first, method: :delete, class:"btn btn-light btn-sm" do %>
                      <span class="glyphicon glyphicon-erase"> <%= @post.inappropiate_posts.count %> </span>
                    <% end %>
                  <% end %>
                  </a>
                  <% if current_user.role == "SuperAdmin" or current_user.role == "Admin" %>
                    <% flag = @post.flags.where("user_id = ?", current_user.id) %>
                    <a>
                    <% if flag.empty? %>
                      <%= button_to flags_path(flag: {post_id: @post.id}), method: :post, class:"btn btn-light btn-sm" do %>
                        <span class="glyphicon glyphicon-flag"> <%= @post.flags.count %> </span> 
                      <% end %>
                    <% else %>
                      <%= button_to flag.first, method: :delete, class:"btn btn-light btn-sm" do %>
                        <span class="glyphicon glyphicon-scissors"> <%= @post.flags.count %> </span>
                      <% end %> 

                    <% end %>
                    </a>
                  <% end %>
                  <!--
                  <% if current_user.id == @post.user_id or current_user.role == "SuperAdmin" or current_user.role == "Admin" %>
                    <a>
                      <button type="button" class="btn btn-light btn-sm">
                        <%= link_to "Edit Post",  edit_post_path(post_id: @post.id) %>
                      </button>  
                    </a>
                  <% end %>
                -->
                </div>
            </div>
          </div>
      </center>
      <%= render 'comments/form', comment: @comment_new %>
      <%= render :partial => 'comments/show' %>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Filch ™ </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="css/bootstrap.css/"/>
    <link type="text/css" rel="stylesheet" href="css/bootstrap.min.css/"/>
    <link type="text/css" rel="stylesheet" href="css/bootstrap-grid.css/"/>
    <link type="text/css" rel="stylesheet" href="css/bootstrap-grid.min.css/"/>
    <link type="text/css" rel="stylesheet" href="css/bootstrap-reboot.css/"/>
    <link type="text/css" rel="stylesheet" href="css/bootstrap-reboot.min.css/"/>

    <link rel="shortcut icon" href="app/assets/images/favicon.ico" type="image/x-icon" />
	<link rel="icon" href="app/assets/images/favicon.ico" type="image/x-icon" /> 
    <!‐‐ Librería jQuery requerida por los plugins de JavaScript ‐‐>
    <script src="http://code.jquery.com/jquery.js"></script>
    <!‐‐ Todos los plugins JavaScript de Bootstrap ‐‐>
    <script src="js/bootstrap.js"> </script>
    <script src="js/bootstrap.min.js"></script>
  </head>
  <style>
    .website{
      margin-left: 70px;
      margin-right: 20px;
    }
  	.filch-title{
  		font-family: "Times New Roman", Times, serif;
  		font-size: 70px;
  		color: black;
  		font-weight: bold;
  		}
  	.policy{
  		color: black;
  		font-size: 20px;
  		background-color: grey;
  	}
    .top-margin{
      margin-top: 20px;
    }
    .container{
      background-color: #cabea9;
      margin-bottom: 2px;
    }
  </style>
  <body style="background-color: peru">
    <header>
    	<div class="container" style="height: auto;" >
    		<div class="jumbotron" style="background-color: #cabea9; height: 200px; ">
    			<div class="page-header" style="height: 170px; margin: 0px;">
    				<div class="row">
  	                <div class="col">
  	                    	<%= image_tag('filch.png', size: '80x120') %>       
  	                </div>

  	                <div class="col">
  	                	<center> <h1 class="filch-title" > FILCH ™</h1> 
                        </br>
                        <% if user_signed_in? %>
                            <%= form_tag(users_show_path method: :get) do %>
                              <%= text_field_tag :name, params[:name] %>
                            <button type="submit">
                              <%= image_tag('search.png', size: '40x30')%> 
                            </button>
                            <% end %>
                        <% end %>
                      </center>
  	                </div>

  	                <div class="col">
  	                	<div class="row float-right">
                        <button type="button" class="btn btn-lg" style="background-color: black; font-weight: bold; display: inline-block; margin-right: 3px;" > 
    	                		<%= link_to('Home', :root) %> </button>
                     
                            <% if user_signed_in? %>
                                <button type="button" class="btn btn-lg" style="background-color: black; font-weight: bold; display: inline-block; margin-right: 3px;">
                                  <% if current_user.image.attached? %>
                                    <%= image_tag(current_user.image, size: '30x40') %>
                                    <%= link_to "Profile", profile_path, class: "button is-info" %>
                                  <% else %>
                                    <%= link_to "Profile", profile_path, class: "button is-info" %>
                                  <% end %>
                                </button>
                                <button type="button" class="btn btn-lg" style="background-color: black; font-weight: bold; display: inline-block;">
                                  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
                                </button>
                                  

                            <% else %>
                              <div class="dropdown show">
                                  <a class="btn btn-link dropdown-toggle btn-lg" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: black; color: #687bc0; font-weight: bold; display: inline-block;">
                                    Join Us
                                  </a>
                                  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" style="font-size: 20px;"> <%= link_to "Log In", new_user_session_path, class: "button is-info" %> </a>
                                    <a class="dropdown-item" style="font-size: 20px;"> <%= link_to "Register", new_user_registration_path, class: "button is-info" %> </a>
                                  </div>
                              </div>
                            <% end %>
                      </div>
  	                </div>
  	            </div>
    			</div>
    		</div>
    	</div>
    </header>



  	<% if notice %>
  		<p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
  		<p class="alert alert-danger"><%= alert %></p>
	<% end %>
    <%= yield %>
    <% if request.url != 'localhost:3000/policy/index' %>
      <center>
        <div class="top-margin">
          <button id="b1" type="submit" class="btn btn-default btn-lg" role="button" style="background-color: black; font-weight: bold"> <%= link_to 'Policy and Terms of Conditions', policy_index_path %></button>
        </div>
      </center>
    <% end %>
  </body>
</html>